site_name: xTrain API
site_url: https://chatelao.github.io/xDuinoRails_xTrainAPI/
repo_url: https://github.com/chatelao/xDuinoRails_xTrainAPI
theme:
  name: readthedocs

docs_dir: gen/site_source
site_dir: gen/public

nav:
  - User Documentation:
    - Home: docs/README.md
    - CLI Syntax: docs/CLI_SYNTAX.md
    - Glossary: docs/XTTRAIN_GLOSSARY.md
  - Contributor Documentation:
    - "Agent Instructions": spec/AGENTS.md
    - "API Reference": docs/API_LINKS.md
    - "Data Dictionary": spec/DATA_DICTIONARY.md
    - "Open Issues": spec/OPEN_ISSUES.md
